library(arm)
setwd('/Users/heatherchen/Desktop/Perspective Spring/Paper/Rawdata')
last <- read.csv('last.csv')
curr_work <- unlist(last['curr_work'])
husband_inc <- unlist(last['husband_inc'])
exper <- unlist(last['exp'])
child_under6 <- unlist(last['child_under6'])
child_6to18 <- unlist(last['child_6to18'])
schooling <- unlist(last['schooling_year'])
indinc <- unlist(last['indinc_cpi'])
constant <- rep(1, 1200)
data = data.frame(constant, curr_work, husband_inc, child_under6, child_6to18, exper, schooling, indinc)
glm.res <- glm( curr_work ~ husband_inc + exper + schooling + child_under6 + child_6to18, offset = indinc, family = binomial, data=data, maxit=1000)
anova(glm.res)
summary(glm.res)
glm.bay <- bayesglm( curr_work ~ husband_inc + exper + schooling + child_under6 + child_6to18, offset = indinc, family = binomial, data=data, maxit=1000)
summary(glm.bay)
